[package]
name = "monirs"
version = "0.0.0"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2018"
license = "ISC"
repository = "https://github.com/ltheinrich/monirs"
description = "Linux monitoring software"
readme = "README.md"

[dependencies]
kern = "1.1.2"

[profile.release]
lto = true
codegen-units = 1
